#pragma config(Sensor, in2,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    LightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  estopBtn,       sensorTouch)
#pragma config(Sensor, dgtl2,  Start,          sensorTouch)
#pragma config(Sensor, dgtl9,  Red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl10, Green,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl11, handshakeIn,    sensorTouch)
#pragma config(Sensor, dgtl12, handshakeOut,   sensorLEDtoVCC)
#pragma config(Motor,  port2,           motor1,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: CIM 11 GIP
  Task Description: Start the handshaking process
*/

task estop()
{
    while(1==1) {
        if(SensorValue(estopBtn) == 1) {
            // Stop all running tasks
            stopAllTasks();
        }

        wait1Msec(10);
    }
}

task main()
{
    // Start the emergency stop task
	startTask(estop);

	// Set LEDs
	turnLEDOn(handshakeOut);
	turnLEDOn(Red);
	turnLEDOff(Green);
    
	// Variable setter
    int runCount;
    runCount = 0;
    int hasTicked;
    hasTicked = 0;

    // Run code if count is less than 4
	while(runCount < 4)
	{
		// Check for start button or backwards handshake signal
		if(SensorValue(Start) == 1 || SensorValue(handshakeIn) == 1) {
			// Set LEDs
			turnLEDOn(Green);
			turnLEDOff(Red);
			wait(5);

            // Turn	motor to 90 degrees using potentiometer
			startMotor(motor1,60);
			untilPotentiometerGreaterThan(90,Potentiometer);
			stopMotor(motor1);

			wait(10);

       while(hasTicked != 1) {
			// Detect if beaker is still in place
			if(SensorValue(LightSensor) <= 100) {
				wait(2);

                // Turn motor to 180 degrees using potentiometer
				startMotor(motor1,60);
				untilPotentiometerGreaterThan(180,Potentiometer);
				stopMotor(motor1);

				wait(2);

                // Turn motor back to 0
				startMotor(motor1,-60);
				untilPotentiometerLessThan(0,Potentiometer);
            	stopMotor(motor1);
				turnLEDOff(Green);
				turnLEDOn(Red);

				// Handshake to config2.c
				turnLEDOff(handshakeOut);
				wait(0.1);
				turnLEDOn(handshakeOut);
			}
		}

		// Iterate run count by 1
        runCount = runCount + 1;
		}
    }
}
