#pragma config(Sensor, in1,    LineFollower,   sensorLineFollower)
#pragma config(Sensor, in2,    Potentiometer,  sensorPotentiometer)
#pragma config(Sensor, in3,    LightSensor,    sensorReflection)
#pragma config(Sensor, dgtl1,  eStopButton,    sensorTouch)
#pragma config(Sensor, dgtl2,  BumpSwitch,     sensorTouch)
#pragma config(Sensor, dgtl3,  Quad,           sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  Sonar,          sensorSONAR_inch)
#pragma config(Sensor, dgtl10, Light,          sensorLEDtoVCC)
#pragma config(Sensor, dgtl12, Green,          sensorLEDtoVCC)
#pragma config(Motor,  port1,           Flashlight,    tmotorVexFlashlight, openLoop, reversed)
#pragma config(Motor,  port2,           rightMotor,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           leftMotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           servoMotor,    tmotorServoStandard, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*
  Project Title: CIM 11 GIP
  Task Description: Start the handshaking process
*/

task estop()
{
    while(1==1)
    	{
        if(SensorValue(dgtl1) == 1)
        	{
            // Stop all running tasks
            stopAllTasks();
        	}

        wait1Msec(10);
    	}
}

task main()
{
    // Start the emergency stop task
	startTask(estop);
turnLEDOn(dgtl12);
    // Variable setter
    int runCount;
    runCount = 0;
    int hasTicked;
    hasTicked = 0;

    // Run code if count is less than 4
	while(runCount < 4)
	{
		if(SensorValue(dgtl2) == 1)							//Button to start entire system
		{

			wait(5);

            // Turn	motor to 90 degrees using potentiometer
			turnLEDOn(dgtl10);
			startMotor(port2,60);
			untilPotentiometerGreaterThan(90,in2);
			stopMotor(port2);

			wait(10);

       while(hasTicked != 1)
       {// Detect if beaker is still in place
					if(SensorValue(LightSensor) <= 100)
					{
						wait(2);

                // Turn motor to 180 degrees using potentiometer
						startMotor(port2,60);
						untilPotentiometerGreaterThan(180,in2);
						stopMotor(port2);

						wait(2);

                // Turn motor back to
						startMotor(port2,-60);
						untilPotentiometerLessThan(0,in2);
            stopMotor(port2);
						turnLEDOff(dgtl10);
						turnLEDOff(dgtl12);
					}
			}

            runCount = runCount + 1;
			}
    }
}
